name: "CI"
on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.2, 3.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install logger and csv
        run: |
          gem install logger
          gem install csv

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test

